# Generated by Django 2.2 on 2019-07-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='esNote_score_model',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('scoreName', models.CharField(max_length=45)),
                ('scoreCreateTime', models.DateTimeField(auto_now_add=True)),
                ('scoreModifyTime', models.DateTimeField(auto_now=True)),
                ('scoreStatus', models.IntegerField()),
                ('scoreInfoJason', models.FileField(upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esNote_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='esNote_score_pic_model',
            fields=[
                ('esNote_score_noteID', models.AutoField(primary_key=True, serialize=False)),
                ('esNote_score_pic', models.ImageField(default='Images/noimg.png', upload_to='')),
                ('score_picModifyTime', models.DateTimeField(auto_now=True)),
                ('esNote_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsNoteScore.esNote_score_model')),
            ],
        ),
    ]
