# Generated by Django 2.2 on 2019-08-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0002_auto_20190825_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esnote_score_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esNote_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
