# Generated by Django 2.2 on 2019-09-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0003_auto_20190825_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esnote_score_model',
            name='scoreInfoJason',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='esnote_score_pic_model',
            name='esNote_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esNote_score_pic', to='EsNoteScore.esNote_score_model'),
        ),
    ]
