# Generated by Django 2.2 on 2019-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0004_auto_20190920_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='esnote_score_pic_model',
            name='order',
            field=models.IntegerField(default=0, null=None),
        ),
    ]
