# Generated by Django 2.2 on 2019-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0008_auto_20191004_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esnote_score_pic_model',
            name='esNote_score_predict_pic',
            field=models.ImageField(default='Images/noimg.png', null=True, upload_to=''),
        ),
    ]
