# Generated by Django 2.2 on 2019-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0010_auto_20191005_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='esnote_score_pic_model',
            name='esNote_score_data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='esnote_score_pic_model',
            name='esNote_score_simple_pic',
            field=models.ImageField(default='Images/noimg.png', upload_to=''),
        ),
    ]
