# Generated by Django 2.2 on 2019-11-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0011_auto_20191031_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esnote_score_model',
            name='scoreInfoJason',
        ),
        migrations.RemoveField(
            model_name='esnote_score_pic_model',
            name='esNote_score_simple_pic',
        ),
    ]
