# Generated by Django 2.2 on 2019-11-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0012_auto_20191102_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='esNote_simple_score_pic_model',
            fields=[
                ('simple_score_ID', models.AutoField(primary_key=True, serialize=False)),
                ('simple_pic', models.ImageField(default='Images/noimg.png', upload_to='')),
                ('score_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_pic', to='EsNoteScore.esNote_score_pic_model')),
            ],
        ),
    ]
