# Generated by Django 2.2 on 2019-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EsNoteScore', '0015_esnote_score_model_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='esnote_score_pic_model',
            name='esNote_score_processed_data',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
