# Generated by Django 2.2.1 on 2019-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sheetMusicPicture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
