# Generated by Django 2.2 on 2019-07-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0002_auto_20190506_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
